### ISSUE TITLE
failing tests when installed as zipped eggs

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#190]
This is mostly a reminder for myself, I'll look into figuring these out.

```
$ python -c "import vsc; print vsc.__file__"
/tmp/eb_zip_safe/lib/python2.7/site-packages/vsc_base-2.2.6-py2.7.egg/vsc/__init__.pyc
$ file /tmp/eb_zip_safe/lib/python2.7/site-packages/vsc_base-2.2.6-py2.7.egg
/tmp/eb_zip_safe/lib/python2.7/site-packages/vsc_base-2.2.6-py2.7.egg: Zip archive data, at least v2.0 to extract
```

```
$ python -m test.runner 2>&1 | tee test.log
.....................F..............FancyLoggerTest blabla

....F........testing with random seed 1336494163495901102
testing with random seed 193175045734673762
testing with random seed 9068181191612786940
testing with random seed 5488078950497625579
testing with random seed 1643309984958261542
testing with random seed 5395455204825461197
testing with random seed 5917419741169374694
testing with random seed 1707551905900217112
testing with random seed 3909794726115846104
testing with random seed 8087890877168203274
...FFFFFFF................
======================================================================
FAIL: test_optcomplete (test.generaloption.GeneralOptionTest)
Test optcomplete support
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/generaloption.py", line 682, in test_optcomplete
    self.assertEqual(ec, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_loggedexception_location (test.exceptions.ExceptionsTest)
Test inclusion of location information in log message for LoggedException.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/exceptions.py", line 175, in test_loggedexception_location
    self.assertTrue(log_re.match(logtxt), "%s matches %s" % (log_re.pattern, logtxt))
AssertionError: ^runpy :: BOOM \(at /.*/vsc/utils/testing.py:[0-9]+ in assertErrorRegex\)$ matches runpy :: BOOM (at build/bdist.macosx-10.10-intel/egg/vsc/utils/testing.py:77 in assertErrorRegex)


======================================================================
FAIL: test_qa_list_of_answers (test.run.TestRun)
Test qa with list of answers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 116, in test_qa_list_of_answers
    self.assertEqual(ec, 0)
AssertionError: 126 != 0

======================================================================
FAIL: test_qa_noqa (test.run.TestRun)
Test noqa
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 102, in test_qa_noqa
    self.assertEqual(ec, RUNRUN_QA_MAX_MISS_EXITCODE)
AssertionError: 126 != 124

======================================================================
FAIL: test_qa_regex (test.run.TestRun)
Test regex based q and a (works only for qa_reg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 93, in test_qa_regex
    self.assertEqual(ec, 0)
AssertionError: 126 != 0

======================================================================
FAIL: test_qa_simple (test.run.TestRun)
Simple testing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 79, in test_qa_simple
    self.assertEqual(ec, 0)
AssertionError: 126 != 0

======================================================================
FAIL: test_simple (test.run.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 58, in test_simple
    self.assertEqual(ec, 0)
AssertionError: 126 != 0

======================================================================
FAIL: test_simple_asyncloop (test.run.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 63, in test_simple_asyncloop
    self.assertEqual(ec, 0)
AssertionError: 126 != 0

======================================================================
FAIL: test_timeout (test.run.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/test/run.py", line 72, in test_timeout
    self.assertEqual(ec, RUNRUN_TIMEOUT_EXITCODE)
AssertionError: 126 != 123

----------------------------------------------------------------------
Ran 75 tests in 26.081s

FAILED (failures=9)
```

**Comment by boegel** [comment]
follow-up in #191
