### ISSUE TITLE
post() broken in vsc.utils.rest

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#229]
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 412, in <module>
    main()
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 275, in main
    cleanup_and_exit = handle_github_options(options, orig_paths)
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 172, in handle_github_options
    new_pr(ec_paths, title=options.pr_title, descr=options.pr_descr, commit_msg=options.pr_commit_msg)
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/github.py", line 740, in new_pr
    status, data = pulls_url.post(body=body)
  File "/Users/kehoste/work/vsc-base/lib/vsc/utils/rest.py", line 145, in post
    headers['Content-Type'] = 'application/json'
TypeError: 'NoneType' object does not support item assignment
```

caused by change in #227 

@JensTimmerman: I hate to say I told you so, but... I told you so; please fix, and add tests to avoid this from happening again

partial fix:
```diff
diff --git a/lib/vsc/utils/rest.py b/lib/vsc/utils/rest.py
index 7dcff2d..9c99fa9 100644
--- a/lib/vsc/utils/rest.py
+++ b/lib/vsc/utils/rest.py
@@ -139,6 +139,9 @@ class Client(object):
         Do a http post request on the given url with given body, headers and parameters
         Parameters is a dictionary that will will be urlencoded
         """
+        if headers is None:
+            headers = {}
+
         if self.append_slash:
             url += '/'
         url += self.urlencode(params)
```

**Comment by JensTimmerman** [comment]
fixed in https://github.com/hpcugent/vsc-base/pull/230

**Comment by boegel** [comment]
#230 merged, so closing this
