### ISSUE TITLE
No github tags/releases

### ISSUE THREAD

**Issue by opoplawski** [hpcugent/vsc-base#232]
I see vsc-base 2.5.1 on pypi, but not in github.

**Comment by boegel** [comment]
@opoplawski 2.5.1 is now also tagged here...

@stdweird, @JensTimmerman: can we somehow automate tagging when we release on PyPI, or at least make a script that complains?

**Comment by stdweird** [comment]
if you do a `python setup.py vsc_release`, it prints the instructions
```
INFO: get token from https://github.com/settings/tokens, set it in GH_OAUTH_TOKEN environment variable
# Run command below to make release on github.com
curl --data '{"body": "Release 0.10.11 for vsc-install version 0.10.11", "name": "0.10.11", "target_commitish": "master", "tag_name": "0.10.11", "prerelease": false, "draft": false}' https://api.github.com/repos/hpcugent/vsc-install/releases?access_token=$GH_OAUTH_TOKEN
INFO: Register with pypi
# Run command below to register with pypi (testpypi False)
python setup.py register sdist upload
```
i now only run the last line to push to pypi, but we could also do the curl thingie (or even using pygithub)

**Comment by opoplawski** [comment]
Thanks.

**Comment by opoplawski** [comment]
Although I cannot build from that:
```
+ /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
INFO: This is (based on) vsc.install.shared_setup 0.10.6
INFO: run_tests from base dir /export/home/orion/redhat/python-vsc-base/vsc-base-vsc-base-2.5.1 (using executable /export/home/orion/redhat/python-vsc-base/vsc-base-vsc-base-2.5.1/setup.py)
INFO: initial packages list: ['vsc', 'vsc.utils']
INFO: generated list: ['vsc', 'vsc.utils']
INFO: generated packages list: ['vsc', 'vsc.utils']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /export/home/orion/redhat/python-vsc-base/vsc-base-vsc-base-2.5.1/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    shared_setup.action_target(PACKAGE)
  File "/usr/lib/python2.7/site-packages/vsc/install/shared_setup.py", line 1354, in action_target
    vsc_setup().action_target(package, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vsc/install/shared_setup.py", line 1340, in action_target
    x = self.parse_target(target, urltemplate)
  File "/usr/lib/python2.7/site-packages/vsc/install/shared_setup.py", line 1175, in parse_target
    target.update(self.get_name_url(version=target['version'], license_name=lic_name))
  File "/usr/lib/python2.7/site-packages/vsc/install/shared_setup.py", line 256, in get_name_url
    raise Exception('no file to get name from')
Exception: no file to get name from
```

**Comment by boegel** [comment]
@opoplawski Is there a particular reason you prefer building from GitHub rather than from PyPI?
The tarball that is uploaded to PyPI is indeed not the same as the 'raw' sources hosted on GitHub, it is pre-processed by `vsc-install`...

**Comment by opoplawski** [comment]
The pypi sources do not contain the tests.

**Comment by JensTimmerman** [comment]
@boegel yes, we can make jenkins do tags when master builds successfully and push to pipy aswell.
But there were people who liked doing int manually ( I don't know why?) so I didn't look into configuring this yet.

**Comment by boegel** [comment]
@stdweird thoughts on included the tests in the releases on PyPI?

**Comment by Flamefire** [comment]
Having tags would also help for seeing when a particular change was introduced and which versions already contain it
