### ISSUE TITLE
fancylogger raiseException support templaiting via args

### ISSUE THREAD

**Issue by stdweird** [hpcugent/vsc-base#233]
`raiseException("%s %s", "a", "b", Exception)` should do the right thing

**Comment by stdweird** [comment]
@JensTimmerman toughts?

**Comment by JensTimmerman** [comment]
personally I would want to remove the raiseException call alltogether. it's not the loggers work to raise exceptions, only to log them.

**Comment by wdpypere** [comment]
I ran into this issue and I agree with @JensTimmerman on this. We should deprecate raiseException and start logging deprecation warnings.

**Comment by wdpypere** [comment]
if we don't deprecate it, it should work like all logger functions.

the quick example is:
```
>>> from vsc.utils import fancylogger
>>> logger = fancylogger.getLogger()
>>> logger.raiseException('test %s%s', "hello", "world")
2021-04-03 13:23:40,401 WARNING    <stdin>         MainThread  test %s%s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wdpypere/.local/lib/python3.9/site-packages/vsc_base-3.2.0-py3.9.egg/vsc/utils/fancylogger.py", line 346, in raiseException
    raise_with_traceback(exception(message))
TypeError: 'str' object is not callable
```

**Comment by stdweird** [comment]
@wdpypere the problem is that people will only raise the exception (which doesn't support the lazy passing of args), and not log, and this makes most of the exceptions problematic to debug.

**Comment by wdpypere** [comment]
I see the issue, but there is nothing preventing users from doing `try ... except Exception ... pass` either, which is arguably even worse. I don't know how far we want to/should go to protect people of shooting themselves in the foot.

 but then raiseException should at least work as all the other logging functions.  I'll have a go at it.

**Comment by wdpypere** [comment]
looking at it, its (as expected) a quite complex problem. As I can see in our code there are 2 main uses for raiseException:

 1. from inside an except block when there is already an Exception
 2. when one wants to create an exception

If we really want to maintain a hybrid error/log thing I would do the same as python itself does it. logging.exception is no more than:
```
def exception(self, msg, *args, exc_info=True, **kwargs):
    self.error(msg, *args, exc_info=exc_info, **kwargs)
```

we could do that with an extra raise included, but that solution would only work for case 1, not for case 2.

**Comment by stdweird** [comment]
i wouldn't spend too much time on it
i just think that having a method for it is better than the all the copy paste, but this breadks the upstream logging module and somewhat hides raises.

but i'm ok with deprecating it.
