### ISSUE TITLE
broken log.deprecated call in SimpleOption

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#236]
```
Traceback (most recent call last):
  File "pr_check.py", line 372, in <module>
    main()
  File "pr_check.py", line 313, in main
    go = simple_option(go_dict=opts, descr="Script to print overview of pull requests for a GitHub repository")
  File "/Users/kehoste/work/vsc-base/lib/vsc/utils/generaloption.py", line 1763, in simple_option
    return SimpleOption(go_dict=go_dict, descr=descr, short_groupdescr=short_groupdescr, long_groupdescr=long_groupdescr, config_files=config_files)
  File "/Users/kehoste/work/vsc-base/lib/vsc/utils/generaloption.py", line 1741, in __init__
    self.log.deprecated('SimpleOption descr argument', '2.5.0', '3.0.0')
TypeError: deprecated() takes exactly 3 arguments (4 given)
```

@stdweird: nice ;)

**Comment by JensTimmerman** [comment]
can you please suply a bit more information?
like your pythonpath etc?
since I can't reproduce this
```
jens@exile ~/w/vsc-base> python 
Python 2.7.11 (default, Aug  9 2016, 15:45:42) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from vsc.utils.generaloption import simple_option
>>> simple_option(go_dict={}, descr="Script to print overview of pull requests for a GitHub repository")
2016-09-02 13:36:41,104 WARNING    <stdin>.SimpleOption MainThread  Deprecated functionality, will no longer work in v3.0.0: SimpleOption descr argument
<vsc.utils.generaloption.SimpleOption object at 0x7f38de125dd0>
>>> 
```

**Comment by boegel** [comment]
nevermind, this is due to `log.deprecated` being redefined in `EasyBuildLog`, I'll fix it there

**Comment by boegel** [comment]
fixed in https://github.com/hpcugent/easybuild-framework/pull/1896

**Comment by stdweird** [comment]
@boegel the reason the deprecation warning is added is because `descr` is completely ignored, you should also address that. we will only remove the named option, not any actual functionlaity (if we ever reach v3 :wink: )
