### ISSUE TITLE
installing vsc-base 2.5.4 with 'setup.py easy_install' fails

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#241]
(this worked fine with vsc-base 2.5.1)

using PyPI sources

```
INFO: This is (based on) vsc.install.shared_setup 0.10.14
INFO: run_tests from base dir /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4 (using executable /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/setup.py)
INFO: initial packages list: ['vsc', 'vsc.utils']
INFO: generated list: ['vsc', 'vsc.utils']
INFO: generated packages list: ['vsc', 'vsc.utils']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url https://github.com/hpcugent/vsc-base in /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/PKG-INFO
INFO: found match name vsc-base in /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/PKG-INFO
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-base', 'name': 'vsc-base'}
INFO: using long_description Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).
INFO: generated list: ['bin/optcomplete.bash', 'bin/startlogdaemon.sh', 'bin/logdaemon.py']
INFO: generated scripts list: ['bin/optcomplete.bash', 'bin/startlogdaemon.sh', 'bin/logdaemon.py']
INFO: no prospector support in py26 (or older)
INFO: running easy_install
INFO: This is (based on) vsc.install.shared_setup 0.10.11
INFO: Creating /user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/vsc-base/2.5.4/lib/python2.6/site-packages/site.py
INFO: Processing .
INFO: Running setup.p
INFO: Running setup.py -q bdist_egg --dist-dir /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/egg-dist-tmp-_NhiGC
INFO: run_tests from base dir /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4 (using executable /tmp/vsc40023/easybuild_build/vscbase/2.5.4/dummy-dummy/vsc-base-2.5.4/setup.py)
INFO: initial packages list: ['vsc', 'vsc.utils']
INFO: generated list: ['vsc', 'vsc.utils']
INFO: generated packages list: ['vsc', 'vsc.utils']
INFO: makesetupcfg set to True, (re)creating setup.cfg
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    shared_setup.action_target(PACKAGE)
  File "external_dist_only/shared_setup_dist_only.py", line 1436, in action_target
    _fvs('action_target function')().action_target(package, *args, **kwargs)
  File "external_dist_only/shared_setup_dist_only.py", line 1424, in action_target
    setupfn(**x)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 452, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 68, in <module>
    shared_setup.action_target(PACKAGE)
  File "external_dist_only/shared_setup_dist_only.py", line 1436, in action_target
    _fvs('action_target function')().action_target(package, *args, **kwargs)
  File "external_dist_only/shared_setup_dist_only.py", line 1422, in action_target
    x = self.parse_target(target, urltemplate)
  File "external_dist_only/shared_setup_dist_only.py", line 1231, in parse_target
    new_target['cmdclass'][name] = getattr(vsc_setup_klass, klass.__name__)
AttributeError: type object 'vsc_setup' has no attribute 'easy_install'
```

**Comment by JensTimmerman** [comment]
this is an issue in vsc-install
