### ISSUE TITLE
import of fancylogger module fails with Python 3.7

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#282]
For some reason I thought we had already ported `vsc-base` to Python 3, but it seems like I'm mis-remembering that... Some progress was made in #280, but it's definitely not complete.

```
PYTHONPATH=$HOME/work/vsc-base/lib python3 -c 'import vsc.utils.fancylogger'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kehoste/work/vsc-base/lib/vsc/utils/fancylogger.py", line 192, in <module>
    logging._levelNames['EXCEPTION'] = logging.ERROR
AttributeError: module 'logging' has no attribute '_levelNames'
```

**Comment by stdweird** [comment]
vsc-install and vsc-base are not supported on py3 atm

**Comment by boegel** [comment]
@stdweird Yeah, I forgot about that after ingesting what we need in EasyBuild and porting stuff there. ;)
