### ISSUE TITLE
daemonize does not work with Py3

### ISSUE THREAD

**Issue by kwaegema** [hpcugent/vsc-base#310]
backupsync stopped working
```
2021-03-10 14:45:24,471 INFO       zkrsync         MainThread  Logging to file /tmp/zkrsync/kyukonhome-dest-4224.log:
Traceback (most recent call last):
  File "/usr/bin/zkrsync", line 293, in <module>
    main()
  File "/usr/bin/zkrsync", line 288, in main
    zkrsdaemon.start()
  File "/usr/lib/python3.6/site-packages/vsc/utils/daemon.py", line 99, in start
    self.daemonize()
  File "/usr/lib/python3.6/site-packages/vsc/utils/daemon.py", line 68, in daemonize
    se = open(self.stderr, 'a+', 0)
ValueError: can't have unbuffered text I/O
```

**Comment by boegel** [comment]
So the question is whether it really need to be unbuffered. If so, we need to use `ba+`. If not, we can just drop the `0`.

As @wdpypere pointed out, this problem was introduced (in some sense, since it still works for Python 2 afaik?) in c5c748109ff6d27e7647e4ed285b760eba781f3c, and we overlooked breaking it because there's no tests (or not enough) covering the code in `daemon.py`.
